apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: petclinic-deployment
  targetAverageUtilization: 50
  
